name: Deploy Pipeline
on:
  workflow_run:
    workflows: ["Code Safety"]
    types:
      - completed
jobs:
  push-to-registry:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . -t gbrandrea/imagenci:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push gbrandrea/imagenci:latest

  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: push-to-registry
    runs-on: ubuntu-latest
    steps:
      - run: curl -X GET "${{ secrets.RENDER_DEPLOY_HOOK }}"
